#[derive(Clone, Copy, Debug, PartialEq)]
pub enum Biome {
    None,
    Ocean,
    Plains,
    Desert,
    ExtremeHills,
    Forest,
    Taiga,
    Swampland,
    River,
    Hell,
    TheEnd,
    FrozenOcean,
    FrozenRiver,
    IcePlains,
    IceMountains,
    MushroomIsland,
    MushroomIslandShore,
    Beach,
    DesertHills,
    ForestHills,
    TaigaHills,
    ExtremeHillsEdge,
    Jungle,
    JungleHills,
    JungleEdge,
    DeepOcean,
    StoneBeach,
    ColdBeach,
    BirchForest,
    BirchForestHills,
    RoofedForest,
    ColdTaiga,
    ColdDaigaHills,
    MegaTaiga,
    MegaTaigaHills,
    ExtremeHillsPlus,
    Savanna,
    SavannaPlateau,
    Mesa,
    MesaPlateauF,
    MesaPlateau,
    TheVoid,
    SunflowerPlains,
    DesertM,
    ExtremeHillsM,
    FlowerForest,
    TaigaM,
    SwamplandM,
    IcePlainsSpikes,
    JungleM,
    JungleEdgeM,
    BirchForestM,
    BirchForestHillsM,
    RoofedForestM,
    ColdTaigaM,
    MegaSpruceTaiga,
    RedwoodTaigaHillsM,
    ExtremeHillsPlusM,
    SavannaM,
    SavannaPlateauM,
    MesaBryce,
    MesaPlateauFM,
    MesaPlateauM,
}

impl From<u8> for Biome {
    fn from(biome_id: u8) -> Self {
        match biome_id {
            0 => Self::Ocean,
            1 => Self::Plains,
            2 => Self::Desert,
            3 => Self::ExtremeHills,
            4 => Self::Forest,
            5 => Self::Taiga,
            6 => Self::Swampland,
            7 => Self::River,
            8 => Self::Hell,
            9 => Self::TheEnd,
            10 => Self::FrozenOcean,
            11 => Self::FrozenRiver,
            12 => Self::IcePlains,
            13 => Self::IceMountains,
            14 => Self::MushroomIsland,
            15 => Self::MushroomIslandShore,
            16 => Self::Beach,
            17 => Self::DesertHills,
            18 => Self::ForestHills,
            19 => Self::TaigaHills,
            20 => Self::ExtremeHillsEdge,
            21 => Self::Jungle,
            22 => Self::JungleHills,
            23 => Self::JungleEdge,
            24 => Self::DeepOcean,
            25 => Self::StoneBeach,
            26 => Self::ColdBeach,
            27 => Self::BirchForest,
            28 => Self::BirchForestHills,
            29 => Self::RoofedForest,
            30 => Self::ColdTaiga,
            31 => Self::ColdDaigaHills,
            32 => Self::MegaTaiga,
            33 => Self::MegaTaigaHills,
            34 => Self::ExtremeHillsPlus,
            35 => Self::Savanna,
            36 => Self::SavannaPlateau,
            37 => Self::Mesa,
            38 => Self::MesaPlateauF,
            39 => Self::MesaPlateau,
            127 => Self::TheVoid,
            129 => Self::SunflowerPlains,
            130 => Self::DesertM,
            131 => Self::ExtremeHillsM,
            132 => Self::FlowerForest,
            133 => Self::TaigaM,
            134 => Self::SwamplandM,
            140 => Self::IcePlainsSpikes,
            149 => Self::JungleM,
            151 => Self::JungleEdgeM,
            155 => Self::BirchForestM,
            156 => Self::BirchForestHillsM,
            157 => Self::RoofedForestM,
            158 => Self::ColdTaigaM,
            160 => Self::MegaSpruceTaiga,
            161 => Self::RedwoodTaigaHillsM,
            162 => Self::ExtremeHillsPlusM,
            163 => Self::SavannaM,
            164 => Self::SavannaPlateauM,
            165 => Self::MesaBryce,
            166 => Self::MesaPlateauFM,
            167 => Self::MesaPlateauM,
            _ => Self::None,
        }
    }
}

impl From<Biome> for u8 {
    fn from(biome: Biome) -> u8 {
        match biome {
            Biome::None => 255,
            Biome::Ocean => 0,
            Biome::Plains => 1,
            Biome::Desert => 2,
            Biome::ExtremeHills => 3,
            Biome::Forest => 4,
            Biome::Taiga => 5,
            Biome::Swampland => 6,
            Biome::River => 7,
            Biome::Hell => 8,
            Biome::TheEnd => 9,
            Biome::FrozenOcean => 10,
            Biome::FrozenRiver => 11,
            Biome::IcePlains => 12,
            Biome::IceMountains => 13,
            Biome::MushroomIsland => 14,
            Biome::MushroomIslandShore => 15,
            Biome::Beach => 16,
            Biome::DesertHills => 17,
            Biome::ForestHills => 18,
            Biome::TaigaHills => 19,
            Biome::ExtremeHillsEdge => 20,
            Biome::Jungle => 21,
            Biome::JungleHills => 22,
            Biome::JungleEdge => 23,
            Biome::DeepOcean => 24,
            Biome::StoneBeach => 25,
            Biome::ColdBeach => 26,
            Biome::BirchForest => 27,
            Biome::BirchForestHills => 28,
            Biome::RoofedForest => 29,
            Biome::ColdTaiga => 30,
            Biome::ColdDaigaHills => 31,
            Biome::MegaTaiga => 32,
            Biome::MegaTaigaHills => 33,
            Biome::ExtremeHillsPlus => 34,
            Biome::Savanna => 35,
            Biome::SavannaPlateau => 36,
            Biome::Mesa => 37,
            Biome::MesaPlateauF => 38,
            Biome::MesaPlateau => 39,
            Biome::TheVoid => 127,
            Biome::SunflowerPlains => 129,
            Biome::DesertM => 130,
            Biome::ExtremeHillsM => 131,
            Biome::FlowerForest => 132,
            Biome::TaigaM => 133,
            Biome::SwamplandM => 134,
            Biome::IcePlainsSpikes => 140,
            Biome::JungleM => 149,
            Biome::JungleEdgeM => 151,
            Biome::BirchForestM => 155,
            Biome::BirchForestHillsM => 156,
            Biome::RoofedForestM => 157,
            Biome::ColdTaigaM => 158,
            Biome::MegaSpruceTaiga => 160,
            Biome::RedwoodTaigaHillsM => 161,
            Biome::ExtremeHillsPlusM => 162,
            Biome::SavannaM => 163,
            Biome::SavannaPlateauM => 164,
            Biome::MesaBryce => 165,
            Biome::MesaPlateauFM => 166,
            Biome::MesaPlateauM => 167,
        }
    }
}
